eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/
server:
  port: 9411
spring:
  application:
    name: zipkin-server
    #rabbitmq配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#zipkin:
#  storage:
#    type: elasticsearch
#    StorageComponent: elasticsearch
#    elasticsearch:
#      cluster: elasticsearch
#      max-requests: 30
#      index: zipkin
#      index-shards: 3
#      index-replicas: 1
#      hosts: localhost:9200

