eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/
server:
  port: 5000
spring:
  application:
    name: service-zuul
zuul:
  routes:
    hiapi:
      path: /hiapi/**
      serviceId: eureka-client
    ribbonapi:
      path: /ribbonapi/**
      serviceId: eureka-ribbon-client
  prefix: /v1