eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/
server:
  port: 8763
spring:
  application:
    name: eureka-client-two
logging:
  file: "logs/eureka-client-two.log"
management:
  security:
    enabled: false